### ISSUE TITLE
Singularity image read-only

### ISSUE THREAD

**Issue by swanux** [gazugafan/AutoLyrixAlignService#1]
If I run it without any manual adjustment, I encounter the following problem:

    (node:45812) UnhandledPromiseRejectionWarning: Error: Command failed: singularity shell kaldi.simg -c "./RunAlignment.sh 
    ../tmp/rLqe9g0Qb3jfw9Hc/test.mp3 ../tmp/rLqe9g0Qb3jfw9Hc/lyrics.txt ../tmp/rLqe9g0Qb3jfw9Hc/aligned.txt"
    ERROR  : Failed to mount squashfs image in (read only): Invalid argument
    ABORT  : Retval = 255

My workaround is to create a writable singularity container and use that one, perhaps there's a better solution though.

**Comment by gazugafan** [comment]
Hmm... some Googling leads me to believe there's a problem running older versions of singularity on newer Linux kernels.
https://github.com/hpcng/singularity/issues/5482
https://github.com/hpcng/singularity/issues/5144

I've only tested on CentOS 8.1.1911. I don't know much about singularity, but I wonder if a newer version would work. I know chitralekha18 mentioned that they only tested on v2.5.2, but maybe there's a newer compatible version where this is fixed?

Or, maybe you could apply the patch mentioned at https://github.com/hpcng/singularity/issues/5144 and recompile singularity?

**Comment by swanux** [comment]
The patch seems to be the most convenient solution. You may implement it by default.
Also, some feedback on other things:

1. The service can't handle filenames with spaces (probably the same case with special characters), but you can easily fix that.
2. The GUI is frozen while aligning (it'd be more user friendly if it wasn't frozen).
3. After alignment, the "post processing" seems to be broken (I guess that's the part where you format the raw output)

> Finished alignment successfully!
> ✔ Done!
> (node:27275) UnhandledPromiseRejectionWarning: TypeError: fs.rm is not a function
> at index (/home/daniel/AutoLyrixAlignService/align.js:116:30)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by gazugafan** [comment]
Auto-patching singularity seems like a really good solution! I created issue #2 for this. Can you confirm that the patch actually solves the problem first, though? I haven't been able to reproduce the problem on any of my machines, so I can't really test it.

**Comment by gazugafan** [comment]
> The service can't handle filenames with spaces (probably the same case with special characters)

Created issue #3 for this.

**Comment by gazugafan** [comment]
> After alignment, the "post processing" seems to be broken

This is probably due to the use of fs.rm, which was added in node v14. I'm guessing you're using an older version of node. No reason to be using fs.rm, though! I'll replace it in #4.

**Comment by gazugafan** [comment]
> The GUI is frozen while aligning (it'd be more user friendly if it wasn't frozen).

I guess I could have it add to a queue in the background. This UI was just suppose to be a simple way to test things out, though.

I kinda want to add an interactive results page, too, where you can click on the words in the lyrics and hear where they were aligned to in the audio file. I'm gonna leave revamping the UI on the backburner for now.

**Comment by gazugafan** [comment]
FYI #3 and #4 are fixed! Spaces in filenames should work. I replaced fs.rm with the rimraf module, which hopefully fixes the problem you're having with JSON formatting. To update, `git pull` and do another `npm install`.

**Comment by gazugafan** [comment]
Went ahead and did the auto-patching of the singularity source code, too. Hopefully it fixes the problem!

Thanks for testing things out. Appreciate your help 😁

**Comment by swanux** [comment]
> Auto-patching singularity seems like a really good solution! I created issue #2 for this. Can you confirm that the patch actually solves the problem first, though? I haven't been able to reproduce the problem on any of my machines, so I can't really test it.

Yes, I can confirm it works.

> This is probably due to the use of fs.rm, which was added in node v14. I'm guessing you're using an older version of node. No reason to be using fs.rm, though! I'll replace it in #4.

Probably that was the issue, as I have node v12 and now it's resolved

> FYI #3 and #4 are fixed! Spaces in filenames should work. I replaced fs.rm with the rimraf module, which hopefully fixes the problem you're having with JSON formatting. To update, `git pull` and do another `npm install`.

Can confirm, it works perfectly.

> Thanks for testing things out. Appreciate your help

Of course. Thank you for this project! My solution was rather industrial, yours is definitely more user focused, which is exactly what I need.

The remaining issues are now only UI related (so not urgent), except maybe that when I select raw output, I get the result without newlines (so one continuous line),

**Comment by gazugafan** [comment]
So glad to hear everything is working!

The raw results should have newlines, but newlines don't render in the browser. If you download the results and open them in notepad or something, you should see the newlines correctly.
