### ISSUE TITLE
Automatic model download from Google Drive not working

### ISSUE THREAD

**Issue by swanux** [gazugafan/AutoLyrixAlignService#5]
Probably an outdated URL or some changes in Google Drive.

**Comment by gazugafan** [comment]
Hmm... seems to be working for me atm. Maybe it was a temporary problem? If not, do you get an error message?

Alternatively, you could just download the file directly from here...
https://docs.google.com/uc?export=download&id=1zJdhPr9SzTVRXIaiZ7eF_QKN0PT2sbIW

Unzip the file into a folder called `NUSAutoLyrixAlign` (in the root of this project) and run `node index.js` again. It should pick it up and ask if you want to apply a patch.

**Comment by swanux** [comment]
Of course, I downloaded the zip manually and it worked, I just mentioned the issue for you to know about it.
Sadly, it persists for me.
Output:

    Downloading data from Google Drive. This is a 3.7G file and may take some time...
    Downloading... [                                        ] 0% | ETA: 0.0sVerifying download...
    ✖ Error: The downloaded file appears to be corrupt.

The result is a .zip file which is a couple of kilobytes only. The output appears immediately.

**Comment by gazugafan** [comment]
weird :(

Thanks for the report. I haven't been able to reproduce it yet, but I'll keep digging.

**Comment by swanux** [comment]
Indeed it is. Luckily it is not a serious issue though. 

Here is some info that might help:
- OS: elementary OS 6
- Node version:  v12.22.6
