### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by noviardi1986** [gazugafan/AutoLyrixAlignService#7]
Hi gazugafan, i manage installed AutoLyrixAlignService on windows wsl,
i can access the page on http://localhost:3000.
but when i test on karaoke forefer it said econnrefused..
Can you help mme to solve the problem?

**Comment by gazugafan** [comment]
Pretty sure that's related to WSL. Have you googled ECONNREFUSED WSL?

**Comment by noviardi1986** [comment]
yes it turn out to be WSL problem. i get the ifconfig command from wsl ubuntu. the ip is 172.26.226.33 so i change the localhost ip in autolyrixalignservis to 172.26.226.33, the  alas is detected..
Thanks Gazuga. Your idea that using youtube video are very great.

**Comment by noviardi1986** [comment]
Now i got 
8/20/2022, 00:57:37   [error] youtube[11916]: Problem processing video #48...
8/20/2022, 00:57:37   [error] youtube[11916]: SyntaxError: Missing catch or finally after try
8/20/2022, 00:57:37    [info] youtube[11916]: There are now 0 processes running
8/20/2022, 00:57:39    [info] youtube[11916]: No more videos to process. Stopping YouTube worker...
8/20/2022, 00:57:39    [info] main[7976]: YouTube processor exited (0)

Can you help me to solve this problem? i can't download video from Youtube that is premix or original... Yesterday where just fine.

**Comment by gazugafan** [comment]
What version of node are you running?

**Comment by noviardi1986** [comment]
it's version 16.16 on windows machine..

**Comment by noviardi1986** [comment]
Turn out to be ytdl-core issue
https://github.com/fent/node-ytdl-core/issues/1113
