### ISSUE TITLE
Request Failed status 400

### ISSUE THREAD

**Issue by noviardi1986** [gazugafan/AutoLyrixAlignService#8]
Hi Gazugafan
after waiting for ytdl-core fix to be working.
i've tried the ALAS there is and error 
8/23/2022, 13:24:48    [info] youtube[14184]: Splitting vocals for video #78...
8/23/2022, 13:24:48    [info] youtube[14184]: Aligning lyrics for video #78...
8/23/2022, 13:24:50   [error] youtube[14184]: Problem processing video #78...
8/23/2022, 13:24:50   [error] youtube[14184]: Error: Request failed with status code 400

Can you help me to solve this Problem? Thank you very much.

**Comment by gazugafan** [comment]
Have you had success with AutoLyrixAlignService and Spleeter outside of the Karaoke Forever fork?

**Comment by noviardi1986** [comment]
No i did not tried yet.. i'll try and post here later.
As for spleeter it has no problem converting if i did not add lyric. it remove vocal flawlessly from karaoke forever..

**Comment by gazugafan** [comment]
Cool! Spleeter is definitely the easier of the two to setup. Best of luck :)

**Comment by noviardi1986** [comment]
Thank Bro. Due to some activities, i haven't tried auto lyrics on outside karaoke forever.. will post soon as i tried
